% order = GetOrderConfig()
%   User should modify the order to fit their needs
%   This acts as a config file
function order = GetOrderConfig()
    % Modify the following list as needed:
    order = { ...
        'Piccolo'; ...
        'Flute'; ...
        'Clarinet'; ...
        'Oboe'; ...
        'Bassoon'; ...
        'Saxophone'; ...
        'Trumpet'; ...
        'Horn'; ...
        'Trombone'; ...
        'Euphonium'; ...
        'Tuba'; ...
        'Percussion' ...
    };
end